START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831121610_AgregarRolesYPrendaUnidad') THEN
    ALTER TABLE detalle_ficha_produccion ADD detalle text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831121610_AgregarRolesYPrendaUnidad') THEN
    CREATE TABLE prenda_unidad (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        detalle_ficha_produccion_id integer NOT NULL,
        controlada boolean NOT NULL,
        fecha_control timestamp without time zone,
        controlado_por_usuario_id integer,
        CONSTRAINT "PK_prenda_unidad" PRIMARY KEY (id),
        CONSTRAINT "FK_prenda_unidad_detalle_ficha_produccion_detalle_ficha_produc~" FOREIGN KEY (detalle_ficha_produccion_id) REFERENCES detalle_ficha_produccion (id) ON DELETE CASCADE,
        CONSTRAINT "FK_prenda_unidad_usuarios_controlado_por_usuario_id" FOREIGN KEY (controlado_por_usuario_id) REFERENCES usuarios (id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831121610_AgregarRolesYPrendaUnidad') THEN
    CREATE INDEX "IX_prenda_unidad_controlado_por_usuario_id" ON prenda_unidad (controlado_por_usuario_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831121610_AgregarRolesYPrendaUnidad') THEN
    CREATE INDEX "IX_prenda_unidad_detalle_ficha_produccion_id" ON prenda_unidad (detalle_ficha_produccion_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831121610_AgregarRolesYPrendaUnidad') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260831121610_AgregarRolesYPrendaUnidad', '10.0.5');
    END IF;
END $EF$;
COMMIT;

