-- 1. Saldo inicial de cada cuenta (uno por cuenta: EFECTIVO, MERCADO PAGO, UALA, ICBC)
CREATE TABLE saldo_inicial_cuenta (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cuenta text NOT NULL,
    fecha timestamp without time zone NOT NULL,
    monto numeric NOT NULL,
    CONSTRAINT "PK_saldo_inicial_cuenta" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX "IX_saldo_inicial_cuenta_cuenta" ON saldo_inicial_cuenta (cuenta);

-- 2. Movimientos manuales (Rendimientos, Pase de Caja, etc.)
CREATE TABLE movimiento_manual_cuenta (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cuenta text NOT NULL,
    fecha timestamp without time zone NOT NULL,
    concepto text NOT NULL,
    monto numeric NOT NULL,
    es_ingreso boolean NOT NULL,
    CONSTRAINT "PK_movimiento_manual_cuenta" PRIMARY KEY (id)
);

CREATE INDEX "IX_movimiento_manual_cuenta_cuenta" ON movimiento_manual_cuenta (cuenta);

-- 3. (Recomendado, no obligatorio) avisarle a Entity Framework que esta migración ya se aplicó.
--    Si tu consola no acepta esta línea, está bien saltearla, no rompe nada de lo de arriba.
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260903140327_AgregarConciliacionCuentas', '10.0.5');
