-- 1. Nueva columna para color/modelo en cada línea de ficha
ALTER TABLE detalle_ficha_produccion ADD COLUMN detalle text;

-- 2. Nueva tabla: una fila por cada prenda física individual
CREATE TABLE prenda_unidad (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    detalle_ficha_produccion_id integer NOT NULL,
    controlada boolean NOT NULL DEFAULT false,
    fecha_control timestamp without time zone,
    controlado_por_usuario_id integer,
    CONSTRAINT "PK_prenda_unidad" PRIMARY KEY (id),
    CONSTRAINT "FK_prenda_unidad_detalle_ficha_produccion" FOREIGN KEY (detalle_ficha_produccion_id) REFERENCES detalle_ficha_produccion (id) ON DELETE CASCADE,
    CONSTRAINT "FK_prenda_unidad_usuarios" FOREIGN KEY (controlado_por_usuario_id) REFERENCES usuarios (id) ON DELETE SET NULL
);

CREATE INDEX "IX_prenda_unidad_controlado_por_usuario_id" ON prenda_unidad (controlado_por_usuario_id);
CREATE INDEX "IX_prenda_unidad_detalle_ficha_produccion_id" ON prenda_unidad (detalle_ficha_produccion_id);

-- 3. (Recomendado, no obligatorio) avisarle a Entity Framework que esta migración ya se aplicó,
--    para que no intente volver a correrla en el futuro. Si tu consola no acepta esta línea,
--    está bien saltearla, no rompe nada de lo de arriba.
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260831121610_AgregarRolesYPrendaUnidad', '10.0.5');
