-- 1. Configuración global del costeador (producción mensual estimada)
CREATE TABLE configuracion_costos (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    produccion_mensual_estimada integer NOT NULL,
    CONSTRAINT "PK_configuracion_costos" PRIMARY KEY (id)
);

-- 2. Gastos generales compartidos (costos productivos + otros gastos)
CREATE TABLE gasto_general (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    monto_mensual numeric NOT NULL,
    tipo integer NOT NULL,
    CONSTRAINT "PK_gasto_general" PRIMARY KEY (id)
);

-- 3. Ficha de costeo por producto
CREATE TABLE costo_producto (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    producto_id integer NOT NULL,
    materia_prima_tela_id integer,
    prendas_por_kg numeric NOT NULL,
    scrap numeric NOT NULL,
    flete numeric NOT NULL,
    cierre numeric NOT NULL,
    elastico_capucha numeric NOT NULL,
    impresion numeric NOT NULL,
    confeccion numeric NOT NULL,
    remarque_porcentaje numeric NOT NULL,
    CONSTRAINT "PK_costo_producto" PRIMARY KEY (id),
    CONSTRAINT "FK_costo_producto_producto_producto_id" FOREIGN KEY (producto_id) REFERENCES producto (id) ON DELETE CASCADE,
    CONSTRAINT "FK_costo_producto_materias_primas_materia_prima_tela_id" FOREIGN KEY (materia_prima_tela_id) REFERENCES materias_primas (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX "IX_costo_producto_producto_id" ON costo_producto (producto_id);
CREATE INDEX "IX_costo_producto_materia_prima_tela_id" ON costo_producto (materia_prima_tela_id);

-- 4. (Recomendado, no obligatorio) avisarle a Entity Framework que esta migración ya se aplicó.
--    Si tu consola no acepta esta línea, está bien saltearla, no rompe nada de lo de arriba.
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260901121800_AgregarCosteador', '10.0.5');
