// <auto-generated />
using System;
using BarsacOMS.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BarsacOMS.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723105134_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarsacOMS.Api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Disciplina")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("disciplina");

                    b.Property<string>("ListaPrecios")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lista_precios");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solicitante");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.Cobro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concepto");

                    b.Property<DateTime>("FechaCobro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_cobro");

                    b.Property<decimal>("Importe")
                        .HasColumnType("numeric")
                        .HasColumnName("importe");

                    b.Property<string>("MedioCobro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("medio_cobro");

                    b.Property<string>("NombreCliente")
                        .HasColumnType("text")
                        .HasColumnName("nombre_cliente");

                    b.Property<string>("NombreOrdenante")
                        .HasColumnType("text")
                        .HasColumnName("nombre_ordenante");

                    b.Property<int?>("OrdenId")
                        .HasColumnType("integer")
                        .HasColumnName("orden_id");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.ToTable("cobros", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.DetallePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("OrdenId")
                        .HasColumnType("integer")
                        .HasColumnName("orden_id");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<string>("Talle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("talle");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("detalle_pedido", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.MateriaPrima", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<int?>("Gramaje")
                        .HasColumnType("integer")
                        .HasColumnName("gramaje");

                    b.Property<decimal?>("MetrosPorRollo")
                        .HasColumnType("numeric")
                        .HasColumnName("metros_por_rollo");

                    b.Property<decimal?>("MetrosRindePorKilo")
                        .HasColumnType("numeric")
                        .HasColumnName("metros_rinde_por_kilo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("NroArticulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nro_articulo");

                    b.Property<decimal?>("PrecioPorKilo")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_por_kilo");

                    b.Property<decimal?>("PrecioPorLitro")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_por_litro");

                    b.Property<decimal?>("PrecioPorRollo")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_por_rollo");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer")
                        .HasColumnName("proveedor_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("materias_primas", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.OrdenTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Disciplina")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("disciplina");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_entrega");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_pedido");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("forma_pago");

                    b.Property<decimal>("ImporteTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_total");

                    b.Property<string>("ListaPrecios")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lista_precios");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_cliente");

                    b.Property<decimal?>("OtrosCobros")
                        .HasColumnType("numeric")
                        .HasColumnName("otros_cobros");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo");

                    b.Property<decimal?>("Senas")
                        .HasColumnType("numeric")
                        .HasColumnName("senas");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solicitante");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("orden_trabajo", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaFactura")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MedioPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.PrecioProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric")
                        .HasColumnName("precio");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<string>("Talle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("talle");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_pago");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("precio_producto", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("producto", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.Cobro", b =>
                {
                    b.HasOne("BarsacOMS.Api.Models.OrdenTrabajo", "Orden")
                        .WithMany()
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.DetallePedido", b =>
                {
                    b.HasOne("BarsacOMS.Api.Models.OrdenTrabajo", "Orden")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarsacOMS.Api.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.MateriaPrima", b =>
                {
                    b.HasOne("BarsacOMS.Api.Models.Proveedor", "Proveedor")
                        .WithMany("MateriasPrimas")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.OrdenTrabajo", b =>
                {
                    b.HasOne("BarsacOMS.Api.Models.Cliente", "Cliente")
                        .WithMany("Ordenes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.PrecioProducto", b =>
                {
                    b.HasOne("BarsacOMS.Api.Models.Producto", "Producto")
                        .WithMany("Precios")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.Cliente", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.OrdenTrabajo", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.Producto", b =>
                {
                    b.Navigation("Precios");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.Proveedor", b =>
                {
                    b.Navigation("MateriasPrimas");
                });
#pragma warning restore 612, 618
        }
    }
}
