// <auto-generated />
using System;
using BarsacOMS.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BarsacOMS.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901121800_AgregarCosteador")]
    partial class AgregarCosteador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarsacOMS.Api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Disciplina")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("disciplina");

                    b.Property<string>("ListaPrecios")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lista_precios");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("localidad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solicitante");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.Cobro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concepto");

                    b.Property<DateTime>("FechaCobro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_cobro");

                    b.Property<decimal>("Importe")
                        .HasColumnType("numeric")
                        .HasColumnName("importe");

                    b.Property<string>("MedioCobro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("medio_cobro");

                    b.Property<string>("NombreCliente")
                        .HasColumnType("text")
                        .HasColumnName("nombre_cliente");

                    b.Property<string>("NombreOrdenante")
                        .HasColumnType("text")
                        .HasColumnName("nombre_ordenante");

                    b.Property<int?>("OrdenId")
                        .HasColumnType("integer")
                        .HasColumnName("orden_id");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.ToTable("cobros", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.ConfiguracionCostos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProduccionMensualEstimada")
                        .HasColumnType("integer")
                        .HasColumnName("produccion_mensual_estimada");

                    b.HasKey("Id");

                    b.ToTable("configuracion_costos", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.CostoProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cierre")
                        .HasColumnType("numeric")
                        .HasColumnName("cierre");

                    b.Property<decimal>("Confeccion")
                        .HasColumnType("numeric")
                        .HasColumnName("confeccion");

                    b.Property<decimal>("ElasticoCapucha")
                        .HasColumnType("numeric")
                        .HasColumnName("elastico_capucha");

                    b.Property<decimal>("Flete")
                        .HasColumnType("numeric")
                        .HasColumnName("flete");

                    b.Property<decimal>("Impresion")
                        .HasColumnType("numeric")
                        .HasColumnName("impresion");

                    b.Property<int?>("MateriaPrimaTelaId")
                        .HasColumnType("integer")
                        .HasColumnName("materia_prima_tela_id");

                    b.Property<decimal>("PrendasPorKg")
                        .HasColumnType("numeric")
                        .HasColumnName("prendas_por_kg");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("RemarquePorcentaje")
                        .HasColumnType("numeric")
                        .HasColumnName("remarque_porcentaje");

                    b.Property<decimal>("Scrap")
                        .HasColumnType("numeric")
                        .HasColumnName("scrap");

                    b.HasKey("Id");

                    b.HasIndex("MateriaPrimaTelaId");

                    b.HasIndex("ProductoId")
                        .IsUnique();

                    b.ToTable("costo_producto", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.DetalleFichaProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archivo")
                        .HasColumnType("boolean")
                        .HasColumnName("archivo");

                    b.Property<bool>("Calandra")
                        .HasColumnType("boolean")
                        .HasColumnName("calandra");

                    b.Property<int>("Cantidades")
                        .HasColumnType("integer")
                        .HasColumnName("cantidades");

                    b.Property<bool>("Corte")
                        .HasColumnType("boolean")
                        .HasColumnName("corte");

                    b.Property<string>("Detalle")
                        .HasColumnType("text")
                        .HasColumnName("detalle");

                    b.Property<bool>("Entregado")
                        .HasColumnType("boolean")
                        .HasColumnName("entregado");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_entrega");

                    b.Property<int>("FichaProduccionId")
                        .HasColumnType("integer")
                        .HasColumnName("ficha_produccion_id");

                    b.Property<bool>("Impresion")
                        .HasColumnType("boolean")
                        .HasColumnName("impresion");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int?>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("producto");

                    b.Property<string>("Talle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("talle");

                    b.HasKey("Id");

                    b.HasIndex("FichaProduccionId");

                    b.ToTable("detalle_ficha_produccion", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.DetallePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("OrdenId")
                        .HasColumnType("integer")
                        .HasColumnName("orden_id");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<string>("Talle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("talle");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("detalle_pedido", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.EntregaParcial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidades")
                        .HasColumnType("integer")
                        .HasColumnName("Cantidades");

                    b.Property<string>("EstadoItem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EstadoItem");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("FechaEntrega");

                    b.Property<int>("FichaProduccionId")
                        .HasColumnType("integer")
                        .HasColumnName("FichaProduccionId");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<int?>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("Numero");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Producto");

                    b.Property<string>("Talle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Talle");

                    b.HasKey("Id");

                    b.HasIndex("FichaProduccionId");

                    b.ToTable("EntregaParcial", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.FichaProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Modista")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modista");

                    b.Property<int>("OrdenId")
                        .HasColumnType("integer")
                        .HasColumnName("orden_id");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.ToTable("ficha_produccion", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.GastoGeneral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MontoMensual")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_mensual");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("gasto_general", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.MateriaPrima", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<int?>("Gramaje")
                        .HasColumnType("integer")
                        .HasColumnName("gramaje");

                    b.Property<decimal?>("MetrosPorRollo")
                        .HasColumnType("numeric")
                        .HasColumnName("metros_por_rollo");

                    b.Property<decimal?>("MetrosRindePorKilo")
                        .HasColumnType("numeric")
                        .HasColumnName("metros_rinde_por_kilo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("NroArticulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nro_articulo");

                    b.Property<decimal?>("PrecioPorKilo")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_por_kilo");

                    b.Property<decimal?>("PrecioPorLitro")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_por_litro");

                    b.Property<decimal?>("PrecioPorRollo")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_por_rollo");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer")
                        .HasColumnName("proveedor_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("materias_primas", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.OrdenTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Disciplina")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("disciplina");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_entrega");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_pedido");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("forma_pago");

                    b.Property<decimal>("ImporteTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_total");

                    b.Property<string>("ListaPrecios")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lista_precios");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_cliente");

                    b.Property<decimal?>("OtrosCobros")
                        .HasColumnType("numeric")
                        .HasColumnName("otros_cobros");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo");

                    b.Property<decimal?>("Senas")
                        .HasColumnType("numeric")
                        .HasColumnName("senas");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solicitante");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("orden_trabajo", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaFactura")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MedioPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.PrecioProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric")
                        .HasColumnName("precio");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<string>("Talle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("talle");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_pago");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("precio_producto", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.PrendaUnidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Controlada")
                        .HasColumnType("boolean")
                        .HasColumnName("controlada");

                    b.Property<int?>("ControladoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("controlado_por_usuario_id");

                    b.Property<int>("DetalleFichaProduccionId")
                        .HasColumnType("integer")
                        .HasColumnName("detalle_ficha_produccion_id");

                    b.Property<DateTime?>("FechaControl")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_control");

                    b.HasKey("Id");

                    b.HasIndex("ControladoPorUsuarioId");

                    b.HasIndex("DetalleFichaProduccionId");

                    b.ToTable("prenda_unidad", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("producto", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.Cobro", b =>
                {
                    b.HasOne("BarsacOMS.Api.Models.OrdenTrabajo", "Orden")
                        .WithMany()
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.CostoProducto", b =>
                {
                    b.HasOne("BarsacOMS.Api.Models.MateriaPrima", "MateriaPrimaTela")
                        .WithMany()
                        .HasForeignKey("MateriaPrimaTelaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BarsacOMS.Api.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MateriaPrimaTela");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.DetalleFichaProduccion", b =>
                {
                    b.HasOne("BarsacOMS.Api.Models.FichaProduccion", null)
                        .WithMany("Items")
                        .HasForeignKey("FichaProduccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.DetallePedido", b =>
                {
                    b.HasOne("BarsacOMS.Api.Models.OrdenTrabajo", "Orden")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarsacOMS.Api.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.EntregaParcial", b =>
                {
                    b.HasOne("BarsacOMS.Api.Models.FichaProduccion", null)
                        .WithMany("EntregasParciales")
                        .HasForeignKey("FichaProduccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.FichaProduccion", b =>
                {
                    b.HasOne("BarsacOMS.Api.Models.OrdenTrabajo", "Orden")
                        .WithMany()
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.MateriaPrima", b =>
                {
                    b.HasOne("BarsacOMS.Api.Models.Proveedor", "Proveedor")
                        .WithMany("MateriasPrimas")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.OrdenTrabajo", b =>
                {
                    b.HasOne("BarsacOMS.Api.Models.Cliente", "Cliente")
                        .WithMany("Ordenes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.PrecioProducto", b =>
                {
                    b.HasOne("BarsacOMS.Api.Models.Producto", "Producto")
                        .WithMany("Precios")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.PrendaUnidad", b =>
                {
                    b.HasOne("BarsacOMS.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ControladoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BarsacOMS.Api.Models.DetalleFichaProduccion", null)
                        .WithMany("Unidades")
                        .HasForeignKey("DetalleFichaProduccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.Cliente", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.DetalleFichaProduccion", b =>
                {
                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.FichaProduccion", b =>
                {
                    b.Navigation("EntregasParciales");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.OrdenTrabajo", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.Producto", b =>
                {
                    b.Navigation("Precios");
                });

            modelBuilder.Entity("BarsacOMS.Api.Models.Proveedor", b =>
                {
                    b.Navigation("MateriasPrimas");
                });
#pragma warning restore 612, 618
        }
    }
}
